# Generated by Django 6.0.2 on 2026-02-24 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('capacity', models.PositiveIntegerField(verbose_name='最大収容人数')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='予約開始日時')),
                ('end_time', models.DateTimeField(verbose_name='予約終了日時')),
                ('is_paid', models.BooleanField(default=False, verbose_name='決済完了フラグ')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QRトークン')),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='OTPコード')),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='OTP有効期限')),
                ('otp_is_used', models.BooleanField(default=False, verbose_name='OTP使用済みフラグ')),
                ('status', models.CharField(choices=[('RESERVED', '予約済み'), ('CHECKED_IN', 'チェックイン済み'), ('CHECKED_OUT', 'チェックアウト済み'), ('CANCELLED', 'キャンセル')], default='RESERVED', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
