# Generated by Django 6.0.2 on 2026-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='otp_failure_count',
            field=models.IntegerField(default=0, verbose_name='OTP認証失敗回数'),
        ),
    ]
